// <auto-generated />
namespace RestLearning.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dboUser_AddedOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dboUser_AddedOn));
        
        string IMigrationMetadata.Id
        {
            get { return "201602031654350_dbo.User_AddedOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
