// <auto-generated />
namespace RestLearning.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dboUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dboUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201602021717251_dbo.Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
